.PHONY: clean All

All:
	@echo "----------Building project:[ challenge_pointer_apply - Debug ]----------"
	@cd "challenge_pointer_apply" && "$(MAKE)" -f  "challenge_pointer_apply.mk"
clean:
	@echo "----------Cleaning project:[ challenge_pointer_apply - Debug ]----------"
	@cd "challenge_pointer_apply" && "$(MAKE)" -f  "challenge_pointer_apply.mk" clean
