.PHONY: clean All

All:
	@echo "----------Building project:[ dynamicMemory - Debug ]----------"
	@cd "dynamicMemory" && "$(MAKE)" -f  "dynamicMemory.mk"
clean:
	@echo "----------Cleaning project:[ dynamicMemory - Debug ]----------"
	@cd "dynamicMemory" && "$(MAKE)" -f  "dynamicMemory.mk" clean
