.PHONY: clean All

All:
	@echo "----------Building project:[ sec10_challenge - Debug ]----------"
	@cd "sec10_challenge" && "$(MAKE)" -f  "sec10_challenge.mk"
clean:
	@echo "----------Cleaning project:[ sec10_challenge - Debug ]----------"
	@cd "sec10_challenge" && "$(MAKE)" -f  "sec10_challenge.mk" clean
