.PHONY: clean All

All:
	@echo "----------Building project:[ cpp_string_practice - Debug ]----------"
	@cd "cpp_string_practice" && "$(MAKE)" -f  "cpp_string_practice.mk"
clean:
	@echo "----------Cleaning project:[ cpp_string_practice - Debug ]----------"
	@cd "cpp_string_practice" && "$(MAKE)" -f  "cpp_string_practice.mk" clean
