.PHONY: clean All

All:
	@echo "----------Building project:[ implement_method2 - Debug ]----------"
	@cd "implement_method2" && "$(MAKE)" -f  "implement_method2.mk"
clean:
	@echo "----------Cleaning project:[ implement_method2 - Debug ]----------"
	@cd "implement_method2" && "$(MAKE)" -f  "implement_method2.mk" clean
